### PR TITLE
Misc fixes

### LINKED ISSUE #43: Two new active devices reported on start of each cast session
On the CAF Nightly when a user initiates a new cast session (before media is selected) two new Active Devices are reported on each cast: The actual cast target (my Nest Hub) with the client name Chromecast 3.0.0, and a ghost "Chromecast." Looking at the dashboard's activity pane, it reports "USER is online from Chromecast" on every connect as if that device is brand new.

If you were to start a cast session, say, three times, there would then be 6 active devices listed at any given time. This behavior wasn't present with the legacy client. Ideally, this "Chromecast" device doesn't get reported at all. [Chromecast 3.0.0 should probably be renamed to Google Cast too?]

image
image

### LINKED ISSUE #63: Receiver always starts playback from the beginning
**Describe the bug**
Receiver always starts playback from the beginning, despite resuming previously played item from web

**To Reproduce**

1. Play previously played item with progress
2. Watch as the receiver will start playing from the beginning

**Expected behavior**

Resume from the correct tick

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.6.4 (unstable)
 - Cast client: Gen 2

### PR DESCRIPTION
**Pull request by hawken93**
Trying to collect small fixes here while the big PR is merged.

Will rebase this after.

Currently in:
* Refactoring mediaManager to playerManager because it's called that in CAF.
* HLS doesn't allow wider streams than the window rez, so limit to window.innerWIdth instead of by device maximums
  * TODO: We should do the same for height, I think portrait mode videos would break without that.
  * TODO: this is bad for directplay and non-hls playback, we should consider reverting this and make mkv the only way to play video. Tough choices ahead. I left the old code commented so it can be easily restored.
* Receiver ID is set after the initial capabilities are reporting, resulting in two devices registered server side. Refactored that inside of JellyfinApi to get it under control and reordered it just a bit more so it obeys the bitrate limit as well (hopefully). Fixes #43
* Getting rid of the extend() method, it just doesn't belong.
* Fixing start seek. Fixes #63
* Fixing playback position reporting
* Fixing stream change that requires transcoding to restart
* Don't tell CAF to completely stop after each item played back
* cap max bitrate to device spec as well.
* Improve bitrate measurement algorithm
* Refactor away window.playlist to get the playlist working
* Start in the middle of a playlist (options.startIndex)

### CODE REVIEW

**Comment by hawken93** [comment]
https://github.com/jellyfin/jellyfin-chromecast/issues/43

**Comment by hawken93** [comment]
Yeah so this means that there is *another* parameter that is arbitrarily restricted when using HLS: Width.
It won't accept any HLS stream that exceeds the actual window width.
Even if it would work.

I suspect that this is used to pick the best stream that makes sense in a scenario where the manifest has many alternatives. For example if you loaded up some youtube video, a cast device connected to 720p would only consider streams up to 720p.

However it would still work for directplay.

This means that we really have to treat direct streamed mkv vs HLS completely differently from a parameter perspective. I also think we need to cap the HLS bitrate based on device because of the inefficient HLS implemenetation.

**Comment by hawken93** [comment]
added #105

**Comment by hawken93** [comment]
Added #102

**Comment by hawken93** [comment]
Added #108

**Comment by hawken93** [comment]
Possible regression on playback of some audio files delivered as opus..

**Comment by hamburglar2160** [comment]
When changing the transcoding stream (enabling subtitles mid-transcode), waitingcontainer covers the video.

**Comment by hawken93** [comment]
Waiting on #93

**Comment by hawken93** [comment]
still want documentmanager in first

**Comment by hawken93** [comment]
I've put this on top of DocumentManager, so this will look nicer after DocumentManager is merged :)

File: src/components/maincontroller.ts [hunk 1]
```diff
@@ -34,16 +32,14 @@ import { MediaSourceInfo } from '~/api/generated/models/media-source-info';
 import { GlobalScope, PlayRequest } from '~/types/global';
 
 window.castReceiverContext = cast.framework.CastReceiverContext.getInstance();
-window.mediaManager = window.castReceiverContext.getPlayerManager();
```
Comment (hawken93) [inline src/components/maincontroller.ts:37]: rationale here is that in CAF it was renamed to PlayerManager, pre-caf it was called MediaManager and they roughly correspond. Using the new name is more intuitive because you don't need a history book to understand it.

**Comment by hawken93** [comment]
Just marked it ready because I don't think the small playback report issue is a dealbreaker considering the fixes here :)

File: src/components/codecSupportHelper.ts [hunk 2]
```diff
@@ -102,22 +102,28 @@ export function getMaxBitrateSupport(): number {
...
+    //    case deviceIds.ULTRA:
+    //    case deviceIds.CCGTV:
+    //        return 3840;
+    //    case deviceIds.GEN1AND2:
+    //    case deviceIds.GEN3:
+    //        return 1920;
+    //    case deviceIds.NESTHUBANDMAX:
+    //        return 1280;
+    //}
+    //return 0;
```
Comment (ferferga) [inline src/components/codecSupportHelper.ts:126]: I think we don't want this comment here to be merged?

File: src/components/commandHandler.ts [hunk 3]
```diff
@@ -138,7 +127,8 @@ export abstract class CommandHandler {
     }
 
     static IdentifyHandler(): void {
-        if (!this.playbackManager.isPlaying()) {
+        if (!PlaybackManager.isPlaying()) {
+            DocumentManager.setAppStatus('waiting');
```
Comment (ferferga) [inline src/components/commandHandler.ts:131]: Can't we make these app status an enum? DocumentManager seems a good place to declare it.

File: src/components/jellyfinActions.ts [hunk 4]
```diff
@@ -198,12 +197,22 @@ export function pingTranscoder(
  */
 export function load(
     $scope: GlobalScope,
-    customData: PlaybackProgressInfo,
+    customData: any,
```
Comment (ferferga) [inline src/components/jellyfinActions.ts:200]: Why?

File: src/components/jellyfinApi.ts [hunk 5]
```diff
@@ -11,28 +11,53 @@ export abstract class JellyfinApi {
...
         this.accessToken = accessToken;
         this.serverAddress = serverAddress;
+
+        // remove special characters from the receiver name
+        receiverName = receiverName.replace(/[^\w\s]/gi, '');
+
+        if (receiverName) {
+            this.deviceName = receiverName;
+            // deviceId just needs to be unique-ish
+            this.deviceId = btoa(receiverName);
```
Comment (ferferga) [inline src/components/jellyfinApi.ts:43]: This is nitpicky but why not generate an UUID or something else? a base64 representation of the device's name is not exactly an id.

We can also use ``sessionId`` from here: https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.system.ApplicationData

File: src/components/maincontroller.ts [hunk 6]
```diff
@@ -3,27 +3,25 @@ import {
...
+    broadcastConnectionErrorMessage
 } from '../helpers';
 import {
+    reportPlaybackStart,
     reportPlaybackProgress,
     reportPlaybackStopped,
     play,
     getPlaybackInfo,
-    stopActiveEncodings,
+    //stopActiveEncodings,
```
Comment (ferferga) [inline src/components/maincontroller.ts:19]: Remove this comment

File: src/components/maincontroller.ts [hunk 7]
```diff
@@ -136,47 +131,71 @@ window.addEventListener('beforeunload', function () {
...
+    cast.framework.events.EventType.PAUSE,
+    (): void => {
+        reportPlaybackProgress($scope, getReportingParams($scope));
+    }
+);
 
-function defaultOnStop(): void {
-    playbackMgr.stop();
+function defaultOnStopped(): void {
+    PlaybackManager.onStopped();
```
Comment (ferferga) [inline src/components/maincontroller.ts:149]:
```suggestion
function defaultOnStop(): void {
    PlaybackManager.onStop();
```

I don't understand very well this arbitrary name change

File: src/components/maincontroller.ts [hunk 8]
```diff
@@ -136,47 +131,71 @@ window.addEventListener('beforeunload', function () {
...
 
-mgr.addEventListener(
+window.playerManager.addEventListener(
     cast.framework.events.EventType.MEDIA_FINISHED,
-    defaultOnStop
+    defaultOnStopped
+);
+window.playerManager.addEventListener(
+    cast.framework.events.EventType.ABORT,
+    defaultOnStopped
```
Comment (ferferga) [inline src/components/maincontroller.ts:158]:
```suggestion
    defaultOnStop
);
window.playerManager.addEventListener(
    cast.framework.events.EventType.ABORT,
    defaultOnStop
```

File: src/components/maincontroller.ts [hunk 9]
```diff
@@ -364,81 +376,44 @@ export function seek(ticks: number): Promise<void> {
...
+    // TODO Could be useful for garbage collection.
+    //      It needs to predict if the server side transcode needs
+    //      to restart.
+    //      Possibility: Always assume it will. Downside: VTT subs switching doesn't
+    //      need to restart the transcode.
+    //const requiresStoppingTranscoding = false;
+    //if (requiresStoppingTranscoding) {
+    //    window.playerManager.pause();
+    //    await stopActiveEncodings($scope.playSessionId);
+    //}
```
Comment (ferferga) [inline src/components/maincontroller.ts:403]: We want those comments as well?

File: src/components/maincontroller.ts [hunk 10]
```diff
@@ -509,23 +484,32 @@ export function shuffle(
 ): Promise<void> {
     return getShuffleItems(data.userId, item).then(function (result) {
         options.items = result.Items;
-        playbackMgr.playFromOptions(data.options);
+        PlaybackManager.playFromOptions(data.options);
     });
 }
 
+/**
+ * This function fetches the full information for an item before playing it.
```
Comment (ferferga) [inline src/components/maincontroller.ts:492]:
```suggestion
 * This function fetches the full information of an item before playing it.
```

File: src/components/maincontroller.ts [hunk 11]
```diff
@@ -509,23 +484,32 @@ export function shuffle(
...
+ * The provided item is not complete.
+ *
+ * Old behavior: The original properties would be copied over to the fetched one,
+ * but just the fetched item should be fine
```
Comment (ferferga) [inline src/components/maincontroller.ts:496]: I think this is not clear enough, I don't understand it for instance 😅.

File: src/components/maincontroller.ts [hunk 12]
```diff
@@ -725,7 +702,12 @@ export function createMediaInformation(
         );
     }
 
-    mediaInfo.customData.startPositionTicks = streamInfo.startPosition || 0;
+    // wtf this breaks everything
+    // mediaInfo.customData.startPositionTicks = streamInfo.startPosition || 0;
+    // try instead:
+    // if(streamInfo.startPosition)
+    //     mediaInfo.customData.startPositionTicks = streamInfo.startPosition
+    // however this is likely to be unneeded
```
Comment (ferferga) [inline src/components/maincontroller.ts:710]: Same comment thing

File: src/components/playbackManager.ts [hunk 13]
```diff
@@ -204,46 +223,92 @@ export class playbackManager {
         loadRequestData.media = mediaInfo;
         loadRequestData.autoplay = true;
 
+        // If we should seek at the start, translate it
+        // to seconds and give it to loadRequestData :)
+        if (mediaInfo.customData.startPositionTicks > 0)
+            loadRequestData.currentTime =
+                mediaInfo.customData.startPositionTicks / 10000000;
```
Comment (ferferga) [inline src/components/playbackManager.ts:230]: Don't we already have a function for translating ticks to seconds?

File: src/components/playbackManager.ts [hunk 14]
```diff
@@ -204,46 +223,92 @@ export class playbackManager {
...
-        const reportingParams = getReportingParams($scope);
+    /**
+     * Called when media stops playing.
+     * TODO avoid doing this between tracks in a playlist
+     */
+    static onStopped(): void {
+        if (this.getNextPlaybackItemInfo()) {
+            $scope.playNextItem = true;
+        } else {
+            $scope.playNextItem = false;
```
Comment (ferferga) [inline src/components/playbackManager.ts:265]:
```suggestion
    static onStop(): void {
        if (this.getNextPlaybackItemInfo()) {
            $scope.playNextItem = true;
        } else {
            $scope.playNextItem = false;
```

File: src/components/playbackManager.ts [hunk 15]
```diff
@@ -204,46 +223,92 @@ export class playbackManager {
...
+
+        if (this.activePlaylistIndex < 0) {
+            // negative = play the first item
+            newIndex = 0;
+        } else
+            switch (window.repeatMode) {
+                case 'RepeatOne':
+                    newIndex = this.activePlaylistIndex;
+                    break;
+                case 'RepeatAll':
```
Comment (ferferga) [inline src/components/playbackManager.ts:295]: IIRC, there's an enum for repeat types included in the CAF typings, at least in the sender's ones.

**Review by ferferga — CHANGES_REQUESTED** [review]

File: src/components/codecSupportHelper.ts (hunk 2 above)
Comment (hawken93) [reply src/components/codecSupportHelper.ts:126]: I did not feel good about deleting it. Each method has its benefits and drawbacks.

Using innerWidth is good for HLS because of the strict checking, however if we don't use HLS and don't get this artificial limitation, we can get more directplays if a chromecast wired up to 720p is able to downscale by itself.

It feels wrong to nuke our knowledge about what devices have which limitation.

Ultimately I think both needs to be implemented, one for HLS, one for directplay types

File: src/components/commandHandler.ts (hunk 3 above)
Comment (hawken93) [reply src/components/commandHandler.ts:131]: I agree

File: src/components/jellyfinActions.ts (hunk 4 above)
Comment (hawken93) [reply src/components/jellyfinActions.ts:200]: I think this type was never actually PlaybackProgressInfo. The scripting throws other properties at it as well. That has to be resolved somehow first, but this looks to be a major refactor on its own

File: src/components/jellyfinApi.ts (hunk 5 above)
Comment (hawken93) [reply src/components/jellyfinApi.ts:43]: You're probably right.

This code has been refactored from maincontroller or stable, don't remember which exactly.

It fixes an error in execution order where nightly will register with the server before the device identity has been set, so after these properties are set it would identify itself differently and hence leave ghost entries in the server device list.

This is the part that I fixed, so my idea here is to just keep it as-is for now, and then we can try to change it and assert that it did not break later on.

File: src/components/maincontroller.ts (hunk 6 above)
Comment (hawken93) [reply src/components/maincontroller.ts:19]: agree

File: src/components/maincontroller.ts (hunk 7 above)
Comment (hawken93) [reply src/components/maincontroller.ts:149]: I changed the names because we need to separate OnStopping from OnStopped.

The events are a mess and a good place to start is to know exactly when an event would fire. This new name is more explicit and allows us to know what will happen if we do certain things in here. The lack of this knowledge seems to have lead to a lot of weird behavior.

For example, this event would be used to report the playback location to the server. However, the playback already stopped so the position that got reported was at 0.

File: src/components/maincontroller.ts (hunk 9 above)
Comment (hawken93) [reply src/components/maincontroller.ts:403]: Well, it's a WIP. I don't know yet what eventually needs to happen in this stream change and on what condition we have to ask the player to pause. I think it could be useful.

File: src/components/jellyfinActions.ts (hunk 4 above)
Comment (hawken93) [reply src/components/jellyfinActions.ts:200]: Ah I remember. This had to be done because I removed the silly extend() function.
Since we now explicitly address the properties in an object, it cannot pretend to be something it isn't anymore :)

File: src/components/maincontroller.ts [hunk 16]
```diff
@@ -136,47 +131,71 @@ window.addEventListener('beforeunload', function () {
...
+        if (!PlaybackManager.playNextItem()) {
+            PlaybackManager.resetPlaylist();
+            PlaybackManager.onStopped();
+        }
     }
-});
+);
+
+// Notify of playback start as soon as the media is playing. Only then is the tick position good.
+window.playerManager.addEventListener(
```
Comment (hawken93) [inline src/components/maincontroller.ts:179]: OnPlaying (When playback has actually started)

File: src/components/maincontroller.ts [hunk 17]
```diff
@@ -136,47 +131,71 @@ window.addEventListener('beforeunload', function () {
...
+    cast.framework.events.EventType.PLAYING,
+    (): void => {
+        reportPlaybackStart($scope, getReportingParams($scope));
+    }
+);
+// Notify of playback end just before stopping it, to get a good tick position
+window.playerManager.addEventListener(
```
Comment (hawken93) [inline src/components/maincontroller.ts:186]: OnStopping (When stop is requested but still playing)

File: src/components/maincontroller.ts (hunk 8 above)
Comment (hawken93) [reply src/components/maincontroller.ts:158]: as above

File: src/components/maincontroller.ts (hunk 16 above)
Comment (hawken93) [reply src/components/maincontroller.ts:179]: Could maybe document this better

File: src/components/maincontroller.ts (hunk 17 above)
Comment (hawken93) [reply src/components/maincontroller.ts:186]: Could maybe document this better

File: src/components/maincontroller.ts [hunk 18]
```diff
@@ -221,37 +240,30 @@ export function processMessage(data: any): void {
...
-        cleanReceiverName || window.deviceInfo.deviceName;
-    // deviceId just needs to be unique-ish
-    window.deviceInfo.deviceId = cleanReceiverName
-        ? btoa(cleanReceiverName)
-        : window.deviceInfo.deviceId;
-
-    if (data.maxBitrate) {
-        window.MaxBitrate = data.maxBitrate;
-    }
-
```
Comment (hawken93) [inline src/components/maincontroller.ts:254]: Here's the source for the refactored deviceId stuff

File: src/components/maincontroller.ts (hunk 11 above)
Comment (hawken93) [reply src/components/maincontroller.ts:496]: will make clearer

File: src/components/maincontroller.ts (hunk 12 above)
Comment (hawken93) [reply src/components/maincontroller.ts:710]: I think I used this comment to discuss it with @YouKnowBlom because I didn't understand where startPosition would be set from, but theoretically the client can set it. I think we may need the second part for resolving a suspected bug. But would need to look over the jellyfin-web code to understand this better.

File: src/components/maincontroller.ts [hunk 19]
```diff
@@ -725,7 +702,12 @@ export function createMediaInformation(
         );
     }
 
-    mediaInfo.customData.startPositionTicks = streamInfo.startPosition || 0;
+    // wtf this breaks everything
+    // mediaInfo.customData.startPositionTicks = streamInfo.startPosition || 0;
```
Comment (hawken93) [inline src/components/maincontroller.ts:706]: these two lines should definitely go away though

File: src/components/playbackManager.ts (hunk 13 above)
Comment (hawken93) [reply src/components/playbackManager.ts:230]: No, we don't actually. I see many places where this division/multiplication is going on. Good idea for a helper function though.

File: src/components/playbackManager.ts (hunk 14 above)
Comment (hawken93) [reply src/components/playbackManager.ts:265]: just skipping this for now

File: src/components/playbackManager.ts (hunk 15 above)
Comment (hawken93) [reply src/components/playbackManager.ts:295]: We should go over both sender and receiver then..

So the sender needs to pick which version to send.

Over at this end, we can support both for a while.

However this will break the stable client, but we can luckily update that now.

**Comment by YouKnowBlom** [comment]
Is this ready to be taken out of draft? @hawken93 

I agree with ferfergas comment about making the appstatus an enum and we should look into giving repeatMode the same treatment, although I have no issue approving this without the latter.

**Comment by mueslimak3r** [comment]
Is this or any other commit that fixes casting music (and playing the correct track, not just starting at the first in an album) going to be merged?

**Comment by neopc10** [comment]
This one

**Comment by SteveDinn** [comment]
Is that the same sort of thing as starting a video file from where you left off? That would be huge for the CC client!

**Comment by mueslimak3r** [comment]
> Is that the same sort of thing as starting a video file from where you left off? That would be huge for the CC client!

I'm not sure about the rest of the fixes. The issue, and fix, that I''m talking about is with chromecast. If I turn on casting, then navigate to an album, and select a song that isn't the first in an album, jellyfin just plays the first song in the album. The bug is that it just won't play any other song/will only start at the beginning of an album when casting. The skip back/forward buttons break when this happens too.

**Comment by neopc10** [comment]
> Is that the same sort of thing as starting a video file from where you left off? That would be huge for the CC client!

It did, and I think still does

**Comment by SteveDinn** [comment]
> It did, and I think still does

Hrm...Not for me. My two biggest issues with the *unstable* CC client is that it doesn't automatically start from where you left off, and it automatically starts playing the same episode or movie again once it finishes. If there is some option or setting I am not aware of, I'd love to know about it.

File: src/components/codecSupportHelper.ts [hunk 20]
```diff
@@ -102,22 +102,28 @@ export function getMaxBitrateSupport(): number {
...
-            return 1920;
-        case deviceIds.NESTHUBANDMAX:
-            return 1280;
-    }
-
-    return 0;
+export function getMaxWidthSupport(): number {
+    // with HLS, it will produce a manifest error if we
+    // send any stream larger than the screen size...
+    return window.innerWidth;
```
Comment (ownbee) [inline src/components/codecSupportHelper.ts:110]: This causes all my videos to be transcodeded even though they can be direct played (setups: CCUltra/4K-TV and CCGen3/FHD-TV). window.innerWidth was 1280 when I tried with gen 2/3 chromecast and a FHD TV. 1920 preferred MaxWidth.

Maybe only use window.innerWidth when HLS stream?

File: src/components/commandHandler.ts [hunk 21]
```diff
@@ -138,7 +130,8 @@ export abstract class CommandHandler {
...
```
Comment (ownbee) [inline src/components/commandHandler.ts:134]: When I tried latest master on jellyfin/jellyfin and jellyfin/jellyfin-web, The identify command was sent from the client while buffering  (after load). isPlaying() returned false here and the receiver went back to "waiting" state  (i.e. "welcome screen") while the video played behind it. Got the same behavior every time I tried. When I removed these actions, it works as expected.

Should this logic really be in the identify command handler? For me, this is looks like side effect. I think more robust guards than isPlaying check must be in place if this is kept.

**Comment by tnyeanderson** [comment]
What will it take to get this out of draft so it can be merged? CC functionality has been so broken to cause constant frustration for a really long time. I am willing to help get this where it needs to be so it can be merged, but we need a checklist or something to find out what needs to be done to get this out of limbo.

Really appreciate everyone's hard work on this project and this PR, let's take it to the hoop :)

**Comment by Vitorvlv** [comment]
Any updates on this?

**Comment by YouKnowBlom** [comment]
Excuse the radio silence, all my focus has gone towards other things lately.

@tnyeanderson I'd take another look at merging it if the changes in my [comment](https://github.com/jellyfin/jellyfin-chromecast/pull/107#issuecomment-889182558) are added, as well as the ones pointed out by Ownbee above. I talked to hawken a while back and he said he did not have the time to dedicate right now so feel free to pick up where he left off.

**Comment by tnyeanderson** [comment]
Thanks @YouKnowBlom ! Here's the checklist:

- [ ] Make `appstatus` an enum
- [ ] Make `repeatMode` an enum
- [ ] Fix null exception - [comment](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r738562716)
- [ ] Only use window.innerWidth when HLS stream - [comment](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r739854539)
- [ ] Identify command - more robust guards than isPlaying check - [comment](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r740335693)

Please let me know anything that should be added to this. Hopefully I'll have some time to take a crack at a few of these this weekend :)

File: src/components/commandHandler.ts (hunk 21 above)
Comment (tnyeanderson) [reply src/components/commandHandler.ts:134]: What do you think of [this](https://github.com/hawken93/jellyfin-chromecast/pull/228/commits/323983aca5a3f2173cd05406d5398831c8e0f153) solution?

File: src/components/commandHandler.ts (hunk 3 above)
Comment (tnyeanderson) [reply src/components/commandHandler.ts:134]: Fixed in https://github.com/hawken93/jellyfin-chromecast/pull/228

File: src/components/playbackManager.ts (hunk 13 above)
Comment (tnyeanderson) [reply src/components/playbackManager.ts:239]: Helper created [here](https://github.com/hawken93/jellyfin-chromecast/pull/228/commits/ffebe175a3f9fbca7180504af9e2d3828a7f5b48) ... is that an appropriate place for the constant or does it belong somewhere else?

File: src/components/playbackManager.ts (hunk 14 above)
Comment (tnyeanderson) [reply src/components/playbackManager.ts:276]: Fixed [here](https://github.com/hawken93/jellyfin-chromecast/pull/228/commits/3fc8967c3ac66b612033e9b2dd09c01cf5168e6f)

File: src/components/playbackManager.ts (hunk 15 above)
Comment (tnyeanderson) [reply src/components/playbackManager.ts:306]: Is [this](https://github.com/hawken93/jellyfin-chromecast/pull/228/commits/8732560cb10621722eb50c013d80918c1675a614) good or does more work need to be done?

File: src/components/codecSupportHelper.ts (hunk 20 above)
Comment (tnyeanderson) [reply src/components/codecSupportHelper.ts:110]: @ownbee what should the value be if it's not an HLS stream (instead of `window.innerWidth`) ?

File: src/components/jellyfinActions.ts (hunk 4 above)
Comment (tnyeanderson) [reply src/components/jellyfinActions.ts:201]: So is this staying as-is?

File: src/components/jellyfinApi.ts [hunk 22]
```diff
@@ -11,28 +11,55 @@ export abstract class JellyfinApi {
...
-            `JellyfinApi.setServerInfo: user:${userId}, token:${accessToken}, server:${serverAddress}`
+            `JellyfinApi.setServerInfo: user:${userId}, token:${accessToken}, ` +
+                `server:${serverAddress}, name:${receiverName}`
         );
         this.userId = userId;
         this.accessToken = accessToken;
         this.serverAddress = serverAddress;
+
+        // remove special characters from the receiver name
+        receiverName = receiverName.replace(/[^\w\s]/gi, '');
```
[the remark this answers is not in the document]
Comment (tnyeanderson) [reply src/components/jellyfinApi.ts:38]: [Fixed](https://github.com/hawken93/jellyfin-chromecast/pull/228/commits/308cc234b1cc062d5e37bf20cd8b41c210cd9b22)

File: src/components/codecSupportHelper.ts (hunk 20 above)
Comment (tnyeanderson) [reply src/components/codecSupportHelper.ts:110]: How does [this](https://github.com/hawken93/jellyfin-chromecast/pull/228/commits/9e668e1e916a5bc123737344d8faa54fb98d03df) look?

**Comment by tnyeanderson** [comment]
I think everything is completed. Awaiting responses on the following questions:

- [ ] Is `customData: any` acceptable [here](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r833957994)?
- [ ] Are we wanting to use the `sessionId` for the `deviceId`? [comment](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r576464839)
- [ ] Are we really wanting to change `defaultOnStopped` to `defaultOnStop` given the argument [here](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r580529898)? I actually think it's clearer as `defaultOnStopped`
- [ ] Did I add the `TicksPerSecond` constant in an appropriate place? [comment](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r833929901)
- [ ] Not sure what to do about [this](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r580535194) or [this](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r580535245)... are changes needed here?
- [ ] General code review to make sure thing are implemented smartly...

I think once these are answered and completed we can finally test and merge (I haven't done any testing yet)

File: src/components/codecSupportHelper.ts (hunk 20 above)
Comment (ownbee) [reply src/components/codecSupportHelper.ts:110]: @tnyeanderson  I think they should be clamped depending on CC-type as it was before. For direct play I think the CC/TV is able to automatically scale if the resolution is too big for the screen (it has worked before). For HLS I have no clue how to solve it.

I fail to see how `h264` coding has anything to do with MaxWidthSupport. If I play a 1920x1080 video with `h264` coding on my FHD TV (1920x1080) do I get the `window.innerWidth` constraint? If so, I would say this is not that great since 95% of my movies are in that format and would be transcoded to lower resolution and put a lot of load on my server.

Problem is, I think, is that the jellyfin server is the one that decides if transcoding is needed and how to stream depending on the constraints chromecast-app reports. Which means this logic suits best to be in the jellyfin server or if we could find something better than `window.innerWidth` or if we could tell it "1920x1080 is okay but if you are going to transcode for other reasons, use `window.innerWidth`".

I'll try find time to test if this works and how `window.innerWidth` behaves this weekend but I can't make a promise.

Thanks for your effort trying to get this in! Really appreciated!

File: src/components/commandHandler.ts (hunk 21 above)
Comment (ownbee) [reply src/components/commandHandler.ts:134]: Looks promising and I am happy with it if it works.

**Comment by Vitorvlv** [comment]
Sorry to keep bothering you people, but any way we can get someone to take a look at tnyeanderson changes?

**Comment by YouKnowBlom** [comment]
First off, thank you for putting in the work @tnyeanderson! Most of my time has gone towards uni work lately, however I should've replied to you much sooner. 

4. Seems like a reasonable place to me. If not it will be simple enough to move.

5. There's some ambiguity in what a "good tick position" is so I think rewriting those comments might be worth it. I assume hawken is talking about the tick position being set to 0 before it is reported?

6. and 7. Will take a close look and leave any suggestions on that PR!

The rest looks good to me, nice work! :)

**Comment by tnyeanderson** [comment]
@YouKnowBlom with how much is riding on this PR, I think we need to reassess the situation and come up with a proper game plan. Pretty much every aspect of chromecast functionality is broken for many users including myself, which is a big deal for such a wonderful media center application. Though this PR may not fix all of these issues, it seems to be a prerequisite for any further changes, and a lot of people are waiting on this.

I am trying to merge the upstream changes in to resolve conflicts (doing this in my [PR](https://github.com/hawken93/jellyfin-chromecast/pull/228), but there has been a lot of refactoring upstream and I'm finding it hard to follow with how unfamiliar I am with the codebase. I was able to overcome this last time, but since the work didn't get merged in before due to falling off the radar, I'm wary of devoting the time to it again for the same result, especially since this time around seems even more difficult.

At this point, I believe it's important to take an honest look at the state of this PR. It is messy, does a TON of stuff, is hard to test and hard to review, has a substantial commit history, and is 2 years old. The longer we wait, the less relevant some of these changes may become (due to being fixed in other ways by refactor, etc)  and the harder it is to track the upstream changes (since it is not being done regularly).

I think we need to do one of two things:

1. Have someone familiar with the codebase go through the merge conflicts and resolve them, then test/review/merge this PR as soon as possible. Further fixes will be done in subsequent PRs. If this makes you nervous, *it should*. With how substantial this PR is, how old it is, and how much has changed upstream, it could be very easy to accidentally introduce a bug this way. I think this is partly the reason this PR hasn't been merged in the first place. It's unmanageable. **That is not to say that I don't appreciate every person who has worked on this PR, and all of the contributors reviewing it, commenting and helping to move it along. I am extremely grateful and I want everyone to get the credit they deserve**. That's why it's so frustrating to me to see all these fixes sitting here unmerged!
2. Take a more holistic approach by reassessing which fixes in this PR's [bullet point list](https://github.com/jellyfin/jellyfin-chromecast/pull/107#issue-777161458) are still needed. Link them directly to associated issues if possible. Then start going through the list making smaller, more manageable PRs for each individual issue (or group of closely related issues). These PRs would hopefully be merged quicker due to being easier to review and test. This PR would be closed but referenced for discussion purposes in the newer PRs.

I think it's clear that I'm on board with number 2 here. I'm very very willing to contribute by cherry picking certain fixes from here and applying them to smaller PRs in hopes that I can get chromecast working.

## $200 BOUNTY

However, if people would prefer option 1 (as it is undeniably *faster*, if more haphazard), then I'm willing to put a $200 bounty on getting this merged. Whoever takes this to the hoop will get it. Unfortunately bountysource is seeing this PR as closed, so I will have to find another way (paypal, snail mail, amazon gift cards, literally anything to get this to work). Unless someone could point me to a better bounty platform?

Again, thank you to everyone who has helped with this PR and with Jellyfin. Let's get this thing done! :)

**Comment by nielsvanvelzen** [comment]
@tnyeanderson as you might have noticed, the development for the casting client is slow. Unfortunately we don't have any active contributors for it right now. If you're willing to create the smaller pull requests I can help out with reviews. I've recently merged a bunch of the smaller (mergeable) pull requests too.

If you want to further discuss the client I encourage you to join our development room on Matrix (https://jellyfin.org/contact/).

**Comment by YouKnowBlom** [comment]
Hey @tnyeanderson,

Like before I've been busy with university as well as all that comes with that. I also haven't used the receiver as much due to being spoiled by the amazing android TV app (Thanks for your hard work @nielsvanvelzen) so I'll have to look into what has changed. Based on my current schedule I should be able to get some work done over the holidays.

Approach 2 is more reasonable but while I can't say how much has changed on the web/server side, there hasn't been any significant changes here (as you know). Therefore I still think this PR is relevant and I hope to get it merged.

My current plan is to have your PR reviewed and updated to reflect the upstream changes by Tuesday. After that I will look into merging this PR once and for all. I'm aiming to have this done by the end of the coming week.

I'm hoping this may reignite the spark that I once had for the receiver, because I do still love it.

**Comment by YouKnowBlom** [comment]
I have successfully merged it on a local branch. Considering how many conflicts there were I think it would be naive to think no bugs have made it in. I'd like to try to test it thoroughly for a few days to make sure everything works like intended. As it seems right now the aim of having a merge ready PR this weekend is still accurate :rocket:

**Comment by YouKnowBlom** [comment]
The last weekend turned out to be a lot busier than I had originally planned. With that said I'm now instead aiming to have it ready for this weekend. Thank you for your patience! 🚀

**Comment by sfwr** [comment]
@YouKnowBlom If it's not going to be merged soon(tm), would you mind pushing your changes onto another branch/fork so we can have a chance to test locally?

**Comment by YouKnowBlom** [comment]
@sfwr Yeah sure! I redid the merge as I wasn't quite happy with it, as well as fixed a few issues preventing me from building but not a whole lot more. I meant to post an update but got lost in the holiday chaos.

The changes are here: https://github.com/YouKnowBlom/jellyfin-chromecast/tree/misc-fixes-tnye-merge

However neither my own receiver ID or the official ones have been updated to reflect the changes yet.

Now that the holiday chaos is starting to calm down I should be able to find some more time. Still need to figure out a better setup to develop on as HDCP ruined my day (I'm away from home currently and won't be back until after new years)

Merry Christmas/Happy holidays!

**Comment by YouKnowBlom** [comment]
Just to give an update, I'm not dead (yet!). I have a version that works fairly well however the current issue is the getMaxWidthSupport function. Currently we check if the video codec is h264 and if so return the window.innerWidth. The problem with this is that seems like innerwidth only ever returns 1280x720 as mentioned by @ownbee [here](https://github.com/jellyfin/jellyfin-chromecast/pull/107#discussion_r835395362). Since we add the width constraint on all h264 playback, not just HLS (which was the original idea), there is a lot of unnecessary transcoding. My attention is currently on restricting the width requirement to HLS (through a codecprofile or similar) however it seems like the server ignores that constraint when applied directly to HLS, so I have not gotten that to work just yet. Once I've figured out a fix for that then this PR is ready.

**Comment by rhysmdnz** [comment]
@YouKnowBlom has there been any progress on this? Is the branch in your repo the latest copy of the code?

**Comment by BloodyIron** [comment]
I too am experiencing really bad UX for the Chromecast from Jellyfin app :( Some details : https://github.com/jellyfin/jellyfin/issues/8457#issuecomment-1668749001 (and some more after that comment)

Really a big bummer since I just spent months trying to figure out the original solution in that issue... only to now experience the new really-bad UX...

Really hoping this repo and releases can get into some good momentum! :)

**Comment by itsmejoeeey** [comment]
Any update on the state of this PR?

> I think it's clear that I'm on board with option 2 here. I'm very very willing to contribute by cherry picking certain fixes from here and applying them to smaller PRs in hopes that I can get chromecast working.

If the maintainers can provide guidance on the best path forward, I'd additionally like to get the ball rolling and contribute towards bring this project back to a working state.

Please let me know.

<hr/>

Although I understand the Android TV app works fine, having the ability to cast to a Chromecast (such as when away from home with friends and family) is an important feature to me - and one that I miss terrible after migrating from Plex.

Although I have done everything I can to get it the best chance of working (HTTPS with Lets Encrypt, loopback NAT and split DNS, valid `Published Server URIs`, etc) - both `Stable` and `Unstable` do not work properly currently.

**Comment by itsmejoeeey** [comment]
@YouKnowBlom @hawken93 @nielsvanvelzen

Considering the state of the repository (completely borked), I don't understand the risk in merging this PR. It will likely fix more than it will break. This PR is effectively blocking any further wider contribution to the repository.

I hope you'll consider just sending it - but ultimately I understand this decision isn't up to me.

If I don't hear anything further, in 10 days I will proceed down the path of creating smaller more manageable PRs from this one.

---

@tnyeanderson Are you still willing to help contribute to this? In 10 days I'll make an issue to track the work of getting this repo back on track.

@nielsvanvelzen Are you still happy to review smaller more manageable PRs if we go down this route?

**Comment by tnyeanderson** [comment]
@sfwr yes that has been known to help in some cases. But in many cases, it's just buggy or flat-out doesn't work anyways.

@itsmejoeeey At this point, I am going to say that I do *not* think that "sending it" is a good answer here. You can posit that this might fix more than it breaks, but how was that determined? This PR is so complex and old that merging it in at this point honestly seems dangerous, unless someone can explain in detail what it does and can thoroughly test it.

It seems clear to me that hardly anyone really knows exactly what this PR does, we are just desperate for a fix. And I am too!

I am absolutely willing to contribute smaller PRs. I think we need to start by dissecting this PR and figuring out all the changes it proposes. Then we should make manageable, atomic goals that can actually be met, reviewed, and merged in a reasonable time.

**Comment by nielsvanvelzen** [comment]
> Considering the state of the repository (completely borked), I don't understand the risk in merging this PR. It will likely fix more than it will break. This PR is effectively blocking any further wider contribution to the repository.
> 
> I hope you'll consider just sending it - but ultimately I understand this decision isn't up to me.
> .... 
> @nielsvanvelzen Are you still happy to review smaller more manageable PRs if we go down this route?

So as you've probably noticed the casting support is not great. This is mainly because none of our contributors use it (most use the native Android TV app that I maintain) and developing for the cast framework is a pain. I'd be willing to help out merging the smaller pull requests but I'm not able to do releases/troubleshooting/complex reviews as my knowledge about the framework is too low. We need to find solutions for that in the long term.

**Comment by BloodyIron** [comment]
I would like to add to the discussion topic that there are those of us who _choose_ to stick to Chromecast devices (in the classical sense) and do not want to switch to Android TV or other such devices. Not trying to say anyone related to Jellyfin stuff is pressuring me (or others) to make the switch, more-so that there are users who intentionally plan (such as myself) to not have a future-path to migrate away from said devices. I have no real way of telling how many there are like this, but I know there's at least one ;)

Either way, I hope Chromecasty stuff for Jellyfin (and related client apps) gets to the point of actually being usable, as in my exhaustive testing (and yes I know I have a complex setup too) I cannot get more than two songs to play before playback just refuses to continue.

**Comment by Sky-High** [comment]
Like others in this thread I am quite interested in the webreceiver as well.

Actually, I have created my own version for testing by merging  https://github.com/YouKnowBlom/jellyfin-chromecast/tree/misc-fixes-tnye-merge with the current unstable, and that works remarkably well. For me many major bottlenecks are removed, and it is much, much better than the current unstable (and in fact, the stable released version). But that might be due to me having only a simple cast setup.

A lot of issues obviously will remain, but hey, no application without bugs ;-) From my point of view, proceeding with the YouKnowBlom/tnyeanderson branch seems easier than taking the current unstable as starting point, but that may well be a personal perspective. I do not understand everything of that branch, but neither do I of the unstable. I intend to continue with gradually fixing some more in my clone, even if it is only out of interest.

I am obviously quite willing to share my fixes if others are interested, but like @itsmejoeeey not sure how to do that. Create my own fork for that? Based on the unstable, or on YouKnowBlom's fork?

If another approach is chosen, I of course don't mind to follow that as well.

**Comment by nielsvanvelzen** [comment]
I will help out with the pull requests opened in this repository targeting the master branch. It should be fine to use the existing open pull requests and fix them (fix conflicts/bugs/pending review comments etc.). All branches from forks that have no pull request to this repository will not be accepted without explicit from the owner of the fork.

When there has been some activity I will discuss future steps for the repository with the Jellyfin team and make the results public.

**Comment by BloodyIron** [comment]
It warms my heart that it looks like this is going in a productive direction <3

**Comment by SteveDinn** [comment]
Oh man, it was clearly a mistake when like 18 months ago, I set my notifications for this project to "All Activity". It was maybe one email a month until today. Then, BAM!

Glad to see things are moving again!

**Comment by nielsvanvelzen** [comment]
Haha sorry about that, I started with _some_ dependency updates but there are a lot. Should be less busy from now on.

**Comment by Sky-High** [comment]
I'll try to submit an appropriate PR after the weekend for review :-)

**Comment by Sky-High** [comment]
As the present PR contains a lot of commits already, it seems cleaner to create a separate PR to just implement the YouKnowBlom/tnyeanderson branch. That PR is https://github.com/jellyfin/jellyfin-chromecast/pull/465.

**Comment by Sky-High** [comment]
@nielsvanvelzen thanks.

I was indeed wondering: jellyfin-web refers to two registered webreceiver app versions

https://github.com/jellyfin/jellyfin-web/blob/25c4da34b2812ec28047f5ae0b6ece17b6afa658/src/plugins/chromecastPlayer/plugin.js#L63-L64

Is the unstable version with applicationID=6F511C87 automatically available when a PR is merged?

I suppose the 'dist' for this is somewhere at a jellyfin server, altough I don't know the URL.

**Comment by nielsvanvelzen** [comment]
Yes, the "unstable" option is automatically deployed from the master branch and the "stable" one is deployed from tags (what you see in the releases tab). They are deployed to apps1.jellyfin.org.

In 10.9 you will be able to customize the available chromecast clients if you want to self-host them / use a developer version / use a third-party one. See discussion [here](https://github.com/jellyfin/jellyfin-meta/issues/45).

**Comment by BloodyIron** [comment]
> Yes, the "unstable" option is automatically deployed from the master branch and the "stable" one is deployed from tags (what you see in the releases tab). They are deployed to apps1.jellyfin.org.
> 
> In 10.9 you will be able to customize the available chromecast clients if you want to self-host them / use a developer version / use a third-party one. See discussion [here](https://github.com/jellyfin/jellyfin-meta/issues/45).

Yay to self-hosting! \o/

**Comment by itsmejoeeey** [comment]
🥳🎉 Exciting!

Big appreciation to the many people that have worked hard to get to this stage. And a big thanks to @Sky-High and @nielsvanvelzen for getting it across the line (especially considering the latter doesn't even make use of this project).

**Comment by BloodyIron** [comment]
How soon before us non-dev plebs can see the fixes in Jellyfin for Chromecast so I can test and see good/bad/ugly results? Also, would I be looking for the stable or unstable version to select? 🤔

**Comment by BloodyIron** [comment]
@nielsvanvelzen okay so I finally got around to testing/validating the "Unstable" Chromecast App in the Jellyfin app. Here's what I found:

1. When testing against a Chromecast that is not blocked from reaching DNS 8.8.8.8 and 8.8.4.4, the Stable AND Unstable Chromecast App setting results in zero playback. This is for music, and video content.
2. When testing against a Chromecast that IS blocked from reaching DNS 8.8.8.8 and 8.8.4.4 (and is fed the DNS servers I have on LAN that are known to work for this and other stuff), Stable results in zero playback. Buuuttt UNSTABLE... so far as I can tell works completely!

So what I did to do blocking, I took the MAC address for the Chromecast I wanted to affect, and created a static IP assignment in my gateway (pfSense), so the DHCP server gives it the same IP every time. In this static IP assignment (via DHCP Server) I also explicitly declare only the gateway as the DNS server, and no other DNS servers (on the internet or on LAN).

I then went over to my friendly-neighbourhood Firewall > Rules section of pfSense, then for the LAN interface added a "Pass" rule with the following parameters (it's at the bottom of the list so I don't think it needs to execute first):

1. Interface LAN
2. Address Family IPv4
3. Protocol TCP/UDP
4. Source, Single host or alias: IP of Chromecast
5. Destination: Single host or alias, 127.0.0.1, Destination Port Range, from DNS (53), to DNS (53)
6. Description: Something useful for future-humans

Then hit save, and APPLY.

It also just occurred to me as I was writing this that I should also validate other Chromecast clients if they can still work against the Chromecast in this configuration, and these apps worked, one on LAN, the other from the internet:

1. Emby (LAN)
2. YouTube
3. Disney+
4. CBC Listen

At this point it looks like EVERYTHING WORKS!

Oh, I also went to the states section of pfSense and confirmed that the affected Chromecast is having it's DNS traffic to 8.8.8.8 and 8.8.4.4 explicitly and 100% reliably redirected to the 127.0.0.1 IP.

Now, I really do appreciate all this work and such! Here are some areas I'm interested in improvement for Jellyfin stuff:

1. Somehow figure out how to make it so the DNS 8.8.8.8 and 8.8.4.4 blocking no longer is needed (Emby doesn't need this, why does Jellyfin? I don't know)
2. Have a new Stable release roll out for the Jellyfin-Chromecast app :^) as it's been uhhh more than two years ;P

Either way this looks 100% workable!!!! Thanks so much! :)))

**Comment by nielsvanvelzen** [comment]
> Somehow figure out how to make it so the DNS 8.8.8.8 and 8.8.4.4 blocking no longer is needed (Emby doesn't need this, why does Jellyfin? I don't know)

This is probably because of your setup. Most apps will set-up a tunnel between their cloud and your local server, so all traffic from your chromecast goes trough that instead. Jellyfin does NOT use cloud servers and we have NO way of sniffing this traffic. The cast receiver needs to connect to your server and to do that it needs to be started with a valid host (DNS resolvable on the public internet or an reachable ip address). 10.9 includes many fixes to prevent the web client from sending "localhost" or "127.0.0.1" as address solving _most_ connectivity issues. I have a prototype branch already that also displays the server address below the "Ready to cast!" text to help figuring out what address is sent.
